// Generated from contracts/help-keys.json by `npm run gen:help-keys`.
// Edit the contract and regenerate; a test fails while this file is stale.

export const HELP_KEYS = [
  "dashboard",
  "dashboard.current-event",
  "dashboard.active-beacon",
  "dashboard.published-state",
  "dashboard.snapshot",
  "dashboard.live-object",
  "dashboard.live-object-cdn",
  "dashboard.email-quota",
  "events",
  "events.create",
  "events.clone",
  "events.set-current",
  "events.delete",
  "events.detail",
  "events.detail.details",
  "events.detail.status",
  "events.detail.status-dialog",
  "events.detail.notify",
  "events.detail.messages",
  "events.detail.seed-cookies",
  "events.detail.flight-history",
  "events.detail.route-map",
  "events.detail.route-map-dialog",
  "events.detail.locations",
  "events.detail.clear-recording",
  "routes",
  "routes.upload",
  "routes.build-from-event",
  "beacons",
  "beacons.create",
  "beacons.key-reveal",
  "beacons.revoked",
  "beacons.detail",
  "beacons.detail.actions",
  "beacons.detail.ages",
  "beacons.detail.fixes",
  "beacons.detail.telemetry",
  "beacons.detail.logs",
  "qr-codes",
  "qr-codes.attach",
  "qr-codes.print-sheet",
  "qr-codes.detail",
  "qr-codes.detail.settings",
  "qr-codes.detail.where",
  "qr-codes.detail.daily",
  "places",
  "places.dialog",
  "places.detail",
  "places.detail.location",
  "places.detail.codes",
  "places.map",
  "places.map.window",
  "scan",
  "scan.attach",
  "pages",
  "pages.status-pages",
  "pages.create",
  "pages.settings",
  "pages.editor",
  "pages.editor.sections",
  "pages.editor.palette",
  "pages.editor.preview",
  "pages.editor.move",
  "pages.editor.autosave",
  "media",
  "media.uploader",
  "media.detail",
  "posters",
  "posters.editor",
  "posters.editor.size",
  "posters.editor.map-details",
  "posters.editor.route-styling",
  "posters.editor.overlays",
  "posters.editor.generate",
  "site-settings",
  "site-settings.identity",
  "site-settings.theme",
  "site-settings.links",
  "site-settings.contact",
  "site-settings.viewpoints",
  "site-settings.places",
  "publish",
  "publish.status",
  "publish.problems",
  "publish.versions",
  "publish.restore",
  "sponsors",
  "sponsors.import",
  "sponsors.detail",
  "sponsors.detail.logo",
  "sponsors.detail.years",
  "sponsors.order",
  "cookie-types",
  "cookie-types.locked",
  "cookie-types.dialog",
  "subscribers",
  "people",
  "contact-messages",
  "settings",
  "settings.poll-interval-ms",
  "settings.cookie-limit-per-person",
  "settings.sponsor-linger-ms-per-dollar",
  "settings.sponsor-linger-min-ms",
  "settings.beacon-stale-after-s",
  "settings.flight-history-max-points",
  "settings.location-min-interval-ms",
  "settings.location-min-distance-m",
  "settings.hub-enabled",
  "settings.route-map-simplify-tolerance-m",
  "settings.route-map-max-points",
  "settings.route-map-default-duration-minutes",
  "api-keys",
  "api-keys.create",
  "api-keys.capabilities",
  "agents",
  "audit",
  "audit.filters",
  "bar.publish",
  "bar.env-badge",
  "drawer",
] as const;

export type HelpKey = (typeof HELP_KEYS)[number];

export const HELP_PAGES: Record<HelpKey, { page: string; label: string }> = {
  "dashboard": { page: "Dashboard", label: "Dashboard overview" },
  "dashboard.current-event": { page: "Dashboard", label: "Current event card" },
  "dashboard.active-beacon": { page: "Dashboard", label: "Active beacon card" },
  "dashboard.published-state": { page: "Dashboard", label: "Published state card" },
  "dashboard.snapshot": { page: "Dashboard", label: "Snapshot card" },
  "dashboard.live-object": { page: "Dashboard", label: "Live object card" },
  "dashboard.live-object-cdn": { page: "Dashboard", label: "CDN and API JSON" },
  "dashboard.email-quota": { page: "Dashboard", label: "Email quota card" },
  "events": { page: "Events", label: "Events list" },
  "events.create": { page: "Events", label: "New event dialog" },
  "events.clone": { page: "Events", label: "Clone event" },
  "events.set-current": { page: "Events", label: "Set current" },
  "events.delete": { page: "Events", label: "Delete event" },
  "events.detail": { page: "Events", label: "Event page" },
  "events.detail.details": { page: "Events", label: "Details card" },
  "events.detail.status": { page: "Events", label: "Status card" },
  "events.detail.status-dialog": { page: "Events", label: "Status dialog" },
  "events.detail.notify": { page: "Events", label: "Notify subscribers" },
  "events.detail.messages": { page: "Events", label: "Messages card" },
  "events.detail.seed-cookies": { page: "Events", label: "Seed cookies card" },
  "events.detail.flight-history": { page: "Events", label: "Flight history card" },
  "events.detail.route-map": { page: "Events", label: "Route map card" },
  "events.detail.route-map-dialog": { page: "Events", label: "Route map dialog" },
  "events.detail.locations": { page: "Events", label: "Locations card" },
  "events.detail.clear-recording": { page: "Events", label: "Clear recording" },
  "routes": { page: "Flight recordings", label: "Flight recordings list" },
  "routes.upload": { page: "Flight recordings", label: "Upload recording" },
  "routes.build-from-event": { page: "Flight recordings", label: "Build from event" },
  "beacons": { page: "Beacons", label: "Beacons list" },
  "beacons.create": { page: "Beacons", label: "New beacon" },
  "beacons.key-reveal": { page: "Beacons", label: "Key reveal dialog" },
  "beacons.revoked": { page: "Beacons", label: "Revoked beacons" },
  "beacons.detail": { page: "Beacons", label: "Beacon page" },
  "beacons.detail.actions": { page: "Beacons", label: "Actions card" },
  "beacons.detail.ages": { page: "Beacons", label: "Ages card" },
  "beacons.detail.fixes": { page: "Beacons", label: "Fixes card" },
  "beacons.detail.telemetry": { page: "Beacons", label: "Telemetry card" },
  "beacons.detail.logs": { page: "Beacons", label: "Logs card" },
  "qr-codes": { page: "QR codes", label: "QR codes list" },
  "qr-codes.attach": { page: "QR codes", label: "Attach to a place" },
  "qr-codes.print-sheet": { page: "QR codes", label: "Print sheet" },
  "qr-codes.detail": { page: "QR codes", label: "QR code page" },
  "qr-codes.detail.settings": { page: "QR codes", label: "Code settings" },
  "qr-codes.detail.where": { page: "QR codes", label: "Where it has been" },
  "qr-codes.detail.daily": { page: "QR codes", label: "Scan statistics" },
  "places": { page: "Places", label: "Places tree" },
  "places.dialog": { page: "Places", label: "Place dialog" },
  "places.detail": { page: "Places", label: "Place page" },
  "places.detail.location": { page: "Places", label: "Location card" },
  "places.detail.codes": { page: "Places", label: "Codes attached here" },
  "places.map": { page: "Places", label: "Places map" },
  "places.map.window": { page: "Places", label: "Map window selects" },
  "scan": { page: "Scan", label: "Scan page" },
  "scan.attach": { page: "Scan", label: "Attach sheet" },
  "pages": { page: "Pages", label: "Pages list" },
  "pages.status-pages": { page: "Pages", label: "Status pages" },
  "pages.create": { page: "Pages", label: "New page dialog" },
  "pages.settings": { page: "Pages", label: "Page settings" },
  "pages.editor": { page: "Pages", label: "Page editor" },
  "pages.editor.sections": { page: "Pages", label: "Section cards" },
  "pages.editor.palette": { page: "Pages", label: "Section palette" },
  "pages.editor.preview": { page: "Pages", label: "Editor preview" },
  "pages.editor.move": { page: "Pages", label: "Move to page" },
  "pages.editor.autosave": { page: "Pages", label: "Automatic saving" },
  "media": { page: "Media", label: "Media library" },
  "media.uploader": { page: "Media", label: "Upload drop zone" },
  "media.detail": { page: "Media", label: "Media detail drawer" },
  "posters": { page: "Poster studio", label: "Poster list" },
  "posters.editor": { page: "Poster studio", label: "Poster editor" },
  "posters.editor.size": { page: "Poster studio", label: "Theme, orientation, size" },
  "posters.editor.map-details": { page: "Poster studio", label: "Map details" },
  "posters.editor.route-styling": { page: "Poster studio", label: "Route styling" },
  "posters.editor.overlays": { page: "Poster studio", label: "Overlays group" },
  "posters.editor.generate": { page: "Poster studio", label: "Generate button" },
  "site-settings": { page: "Site settings", label: "Site settings form" },
  "site-settings.identity": { page: "Site settings", label: "Name and logo" },
  "site-settings.theme": { page: "Site settings", label: "Theme switches" },
  "site-settings.links": { page: "Site settings", label: "Menu and footer links" },
  "site-settings.contact": { page: "Site settings", label: "Contact and analytics" },
  "site-settings.viewpoints": { page: "Site settings", label: "Viewpoints list" },
  "site-settings.places": { page: "Site settings", label: "Places on the maps" },
  "publish": { page: "Publish", label: "Publish page" },
  "publish.status": { page: "Publish", label: "Status card" },
  "publish.problems": { page: "Publish", label: "Problems list" },
  "publish.versions": { page: "Publish", label: "Versions list" },
  "publish.restore": { page: "Publish", label: "Restore a version" },
  "sponsors": { page: "Sponsors", label: "Sponsors list" },
  "sponsors.import": { page: "Sponsors", label: "Import from year" },
  "sponsors.detail": { page: "Sponsors", label: "Sponsor page" },
  "sponsors.detail.logo": { page: "Sponsors", label: "Logo card" },
  "sponsors.detail.years": { page: "Sponsors", label: "Years card" },
  "sponsors.order": { page: "Sponsors", label: "Sponsor order" },
  "cookie-types": { page: "Cookie types", label: "Cookie types list" },
  "cookie-types.locked": { page: "Cookie types", label: "Locked while live" },
  "cookie-types.dialog": { page: "Cookie types", label: "Cookie type dialog" },
  "subscribers": { page: "Subscribers", label: "Subscribers list" },
  "people": { page: "People", label: "People list" },
  "contact-messages": { page: "Contact messages", label: "Contact messages" },
  "settings": { page: "Settings", label: "Settings list" },
  "settings.poll-interval-ms": { page: "Settings", label: "Poll interval" },
  "settings.cookie-limit-per-person": { page: "Settings", label: "Cookie limit" },
  "settings.sponsor-linger-ms-per-dollar": { page: "Settings", label: "Sponsor time per dollar" },
  "settings.sponsor-linger-min-ms": { page: "Settings", label: "Minimum sponsor time" },
  "settings.beacon-stale-after-s": { page: "Settings", label: "Beacon stale threshold" },
  "settings.flight-history-max-points": { page: "Settings", label: "Flight history points" },
  "settings.location-min-interval-ms": { page: "Settings", label: "Minimum fix interval" },
  "settings.location-min-distance-m": { page: "Settings", label: "Minimum fix distance" },
  "settings.hub-enabled": { page: "Settings", label: "Hub enabled" },
  "settings.route-map-simplify-tolerance-m": { page: "Settings", label: "Route map tolerance" },
  "settings.route-map-max-points": { page: "Settings", label: "Route map max points" },
  "settings.route-map-default-duration-minutes": { page: "Settings", label: "Default route duration" },
  "api-keys": { page: "API keys", label: "API keys list" },
  "api-keys.create": { page: "API keys", label: "New key dialog" },
  "api-keys.capabilities": { page: "API keys", label: "Capability list" },
  "agents": { page: "Agents", label: "Agents page" },
  "audit": { page: "Audit", label: "Audit log" },
  "audit.filters": { page: "Audit", label: "Audit filters" },
  "bar.publish": { page: "Navigation", label: "Publish button" },
  "bar.env-badge": { page: "Navigation", label: "Environment badge" },
  "drawer": { page: "Navigation", label: "Navigation drawer" },
};
